// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Character struct {
	ID          int64
	UserID      int64
	Gender      string
	RegionID    int64
	MapID       int64
	X           int64
	Z           int64
	Health      int64
	MaxHealth   int64
	Speed       int64
	RotationY   float64
	WeaponSlot  int64
	IsCrouching int64
}

type CharacterWeapon struct {
	CharacterID int64
	SlotIndex   int64
	WeaponName  string
	WeaponType  string
	Ammo        int64
	ReserveAmmo int64
	FireMode    int64
	DisplayName string
}

type User struct {
	ID           int64
	Username     string
	Nickname     string
	PasswordHash string
	CharacterID  sql.NullInt64
}
