// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Character struct {
	ID       int64
	UserID   int64
	Gender   string
	RegionID int64
	MapID    int64
	X        int64
	Z        int64
	Hp       int64
	MaxHp    int64
}

type User struct {
	ID           int64
	Username     string
	Nickname     string
	PasswordHash string
	CharacterID  sql.NullInt64
}
